name: Elixir CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            
          - name: Setup BEAM & Elixir
            uses: erlef/setup-beam@v1.18.2
            with:
                otp-version: '27'
                elixir-version: '1.18'

          - name: Install dependencies
            run: mix deps.get

          - name: Compile the project
            run: mix compile

          - name: Run tests
            run: mix test