name: Elixir CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Elixir
            uses: actions/setup-elixir@v1
            with:
              otp-version: '27.x'
              elixir-version: '1.18.x'

          - name: Install dependencies
            run: mix deps.get

          - name: Compile the project
            run: mix compile

          - name: Run tests
            run: mix test